// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use VITE_ prefix for environment variables in Vite projects
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "https://nodxpgdulvnuvpbwkgzz.supabase.co";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZHhwZ2R1bHZudXZwYndrZ3p6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMzIzNzAsImV4cCI6MjA2MzYwODM3MH0.T13s1F097F79HysTduG2bWj6SZ4Nw7-F0N9oKbL6K7w";

// Optional: Service role key (required for admin operations)
// For security, you should use this only on the server side, not in the client
const SUPABASE_SERVICE_ROLE_KEY = import.meta.env.VITE_SUPABASE_SERVICE_ROLE_KEY || '';

// Check for required environment variables
if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  console.warn("WARNING: Supabase credentials might be missing. Using fallback values.");
}

console.log("Initializing Supabase client with URL:", SUPABASE_URL);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create Supabase client with simple password-based auth (no email verification)
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: false, // Don't look for auth redirects in URL
    flowType: 'implicit', // Use simpler auth flow
    debug: true, // Enable debug logging in development
    // Configure session storage with better error handling
    storage: {
      getItem: (key) => {
        try {
          const value = localStorage.getItem(key);
          console.log(`Retrieved auth key ${key}: ${value ? 'Found' : 'Not found'}`);
          return value;
        } catch (error) {
          console.error('Error accessing localStorage:', error);
          return null;
        }
      },
      setItem: (key, value) => {
        try {
          console.log(`Storing auth key ${key}`);
          localStorage.setItem(key, value);
        } catch (error) {
          console.error('Error setting localStorage:', error);
        }
      },
      removeItem: (key) => {
        try {
          console.log(`Removing auth key ${key}`);
          localStorage.removeItem(key);
        } catch (error) {
          console.error('Error removing localStorage item:', error);
        }
      }
    }
  },
  // Configure global request settings with proper error handling
  global: {
    headers: {
      'X-Client-Info': 'CodeStruct Client'
    },
    // Add request hooks to help debug issues
    fetch: (url, options) => {
      // Log all auth-related API calls
      if (url.toString().includes('/auth/')) {
        console.log(`Auth API call: ${options?.method || 'GET'} ${url.toString()}`);
      }
      return fetch(url, {
        ...options,
        // Ensure reasonable timeout
        signal: options?.signal || AbortSignal.timeout(10000),
      });
    }
  },
  // Configure real-time for better consistency
  realtime: {
    params: {
      eventsPerSecond: 10
    }
  }
});

// Create an admin client if service role key is available
// This should ONLY be used for admin operations
export const adminSupabase = SUPABASE_SERVICE_ROLE_KEY 
  ? createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      auth: {
        autoRefreshToken: false,
        persistSession: false
      }
    })
  : null;

// Initial session check with better error handling
(async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    if (error) {
      console.error("Error getting initial session:", error.message);
    } else if (data?.session) {
      console.log("Current user session found:", data.session.user.email);
      
      // Check for existence of user profile
      const { data: profileData, error: profileError } = await supabase
        .from('profiles')
        .select('id')
        .eq('id', data.session.user.id)
        .single();
        
      if (profileError && profileError.code !== 'PGRST116') { // Not found error
        console.error("Error checking user profile:", profileError);
      } else if (!profileData) {
        console.log("Profile not found for user, will be created when needed");
      }
    } else {
      console.log("No user is currently logged in");
    }
  } catch (err) {
    console.error("Error checking initial session:", err);
  }
})();

// Add debugging helpers to window for easier troubleshooting
if (typeof window !== 'undefined') {
  // @ts-ignore - Add to window for debugging
  window.supabaseClient = supabase;
  
  // @ts-ignore - Add helper functions
  window.supabaseDebug = {
    getSession: async () => {
      const { data, error } = await supabase.auth.getSession();
      console.log('Current session:', data?.session ? 'Found' : 'None', error || '');
      return { data, error };
    },
    checkUser: async (email: string) => {
      try {
        // Use type assertion to bypass TypeScript checking
        const { data, error } = await (supabase.rpc as any)('check_user_exists', { user_email: email });
        console.log('User check result:', data, error || '');
        return { data, error };
      } catch (e) {
        console.error('Error in checkUser:', e);
        return { error: e };
      }
    },
    confirmUser: async (email: string) => {
      try {
        // Use type assertion to bypass TypeScript checking
        const { data, error } = await (supabase.rpc as any)('manually_confirm_user', { user_email: email });
        console.log('Manual confirmation result:', error ? 'Failed' : 'Success', error || '');
        return { data, error };
      } catch (e) {
        console.error('Error in confirmUser:', e);
        return { error: e };
      }
    }
  };
}